"""create_all_tables

Revision ID: 18a95e2da077
Revises: 
Create Date: 2026-07-27 12:36:26.991644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18a95e2da077'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ignore_hidden', sa.Boolean(), nullable=False),
    sa.Column('ignore_node_modules', sa.Boolean(), nullable=False),
    sa.Column('max_file_size', sa.BigInteger(), nullable=False),
    sa.Column('custom_ignore_globs', sa.ARRAY(sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folder_path', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='scanstatus'), nullable=False),
    sa.Column('total_files', sa.Integer(), nullable=True),
    sa.Column('total_size', sa.BigInteger(), nullable=True),
    sa.Column('total_lines', sa.BigInteger(), nullable=True),
    sa.Column('settings_snapshot', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scanned_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('full_path', sa.Text(), nullable=False),
    sa.Column('extension', sa.Text(), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('line_count', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scanned_files_extension'), 'scanned_files', ['extension'], unique=False)
    op.create_index(op.f('ix_scanned_files_scan_id'), 'scanned_files', ['scan_id'], unique=False)
    op.create_index(op.f('ix_scanned_files_sha256'), 'scanned_files', ['sha256'], unique=False)
    op.create_table('duplicates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('file1_id', sa.Integer(), nullable=False),
    sa.Column('file2_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file1_id'], ['scanned_files.id'], ),
    sa.ForeignKeyConstraint(['file2_id'], ['scanned_files.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_duplicates_scan_id'), 'duplicates', ['scan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_duplicates_scan_id'), table_name='duplicates')
    op.drop_table('duplicates')
    op.drop_index(op.f('ix_scanned_files_sha256'), table_name='scanned_files')
    op.drop_index(op.f('ix_scanned_files_scan_id'), table_name='scanned_files')
    op.drop_index(op.f('ix_scanned_files_extension'), table_name='scanned_files')
    op.drop_table('scanned_files')
    op.drop_table('scans')
    op.drop_table('scan_settings')
    # ### end Alembic commands ###
